<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Product extends Model
{
    use HasFactory;

    const IMAGE_WIDTH = 716;
    const IMAGE_HEIGHT = 930;

    protected $appends = ['image_url'];

    protected $fillable = [
        'title',
        'slug',
        'description',
        'price',
    ];

    /**
     * Get the user's referral link.
     *
     * @return string
     */
    public function getImageUrlAttribute(): string
    {
        return $this->image_url = $this->image->url;
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Product $product) {
            $product->slug = Str::slug($product->title);
        });

        static::updating(function (Product $product) {
            $product->slug = Str::slug($product->title);
        });
    }

    public function image(): \Illuminate\Database\Eloquent\Relations\MorphOne
    {
        return $this->morphOne(Image::class, 'imageable');
    }

}
